name: CI for StudyBuddy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run type-check and tests
    - name: Run TypeScript type-check
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test
